// flow-typed signature: 486204029648fe2fe81154d7d6a1e998
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-free-solid_v0.0.15/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-free-solid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-free-solid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-free-solid/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-free-solid/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-solid/index.es'>;
}
declare module '@fortawesome/fontawesome-free-solid/index' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-solid'>;
}
declare module '@fortawesome/fontawesome-free-solid/index.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-solid'>;
}
