// flow-typed signature: c384e4d4450c0d8e384f58afe1e1e498
// flow-typed version: <<STUB>>/eslint-formatter-summary_v^1.0.1/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-formatter-summary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-formatter-summary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-formatter-summary/dist/aggregator' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/extract-messages' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/find-rule' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/format-results' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/length-of-longest' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/pad-num' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/parse-cli-args' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/process-message' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/sort-by-prop' {
  declare module.exports: any;
}

declare module 'eslint-formatter-summary/dist/sum-up' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-formatter-summary/dist/aggregator.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/aggregator'>;
}
declare module 'eslint-formatter-summary/dist/extract-messages.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/extract-messages'>;
}
declare module 'eslint-formatter-summary/dist/find-rule.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/find-rule'>;
}
declare module 'eslint-formatter-summary/dist/format-results.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/format-results'>;
}
declare module 'eslint-formatter-summary/dist/length-of-longest.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/length-of-longest'>;
}
declare module 'eslint-formatter-summary/dist/pad-num.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/pad-num'>;
}
declare module 'eslint-formatter-summary/dist/parse-cli-args.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/parse-cli-args'>;
}
declare module 'eslint-formatter-summary/dist/process-message.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/process-message'>;
}
declare module 'eslint-formatter-summary/dist/sort-by-prop.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/sort-by-prop'>;
}
declare module 'eslint-formatter-summary/dist/sum-up.js' {
  declare module.exports: $Exports<'eslint-formatter-summary/dist/sum-up'>;
}
declare module 'eslint-formatter-summary/index' {
  declare module.exports: $Exports<'eslint-formatter-summary'>;
}
declare module 'eslint-formatter-summary/index.js' {
  declare module.exports: $Exports<'eslint-formatter-summary'>;
}
