// flow-typed signature: a2cd9f325fb9eb141888c709600edc0b
// flow-typed version: <<STUB>>/react-router-redux_v5.0.0-alpha.9/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-redux' {
  declare module.exports: any;
}
