// flow-typed signature: 271d1680e018a4e10f8bbfdbcac3270d
// flow-typed version: <<STUB>>/react-sortable-hoc_v0.8.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortable-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortable-hoc' {
  declare module.exports: any;
}
