/*
 * @flow
 */

export const EDM_PRIMITIVE_TYPES :string[] = [
  'Binary',
  'Boolean',
  'Byte',
  'SByte',
  'Date',
  'DateTimeOffset',
  'TimeOfDay',
  'Duration',
  'Decimal',
  'Single',
  'Double',
  'Guid',
  'Int16',
  'Int32',
  'Int64',
  'String',
  'Stream',
  'Geography',
  'GeographyPoint',
  'GeographyLineString',
  'GeographyPolygon',
  'GeographyMultiPoint',
  'GeographyMultiLineString',
  'GeographyMultiPolygon',
  'GeographyCollection',
  'Geometry',
  'GeometryPoint',
  'GeometryLineString',
  'GeometryPolygon',
  'GeometryMultiPoint',
  'GeometryMultiLineString',
  'GeometryMultiPolygon',
  'GeometryCollection'
];
